apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: recentimagery
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: PORT
            value: "4503"
          - name: ENVIRONMENT
            value: staging
          - name: LOCAL_URL
            value: http://{name}.gfw.svc.cluster.local:4503
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: EE_PRIVATE_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: EE_PRIVATE_KEY
        ports:
          - containerPort: 4503

      restartPolicy: Always
